logging:
  config: classpath:log4j2-local.xml
  level:
    root: warn


api_auth:
  - api_id: 352695
    api_key: "xxxxxx"
    api_secret: ""
  - api_id: 352693
    api_key: "xxxxxx"
    api_secret: ""

storage_meta:
  - aliyun:
      - mifish-video-1:
          hosts:
            - host: mifish.video1.cdn.outer.com
              tags:
                - jdcdn
                - wangsucdn
            - host: mifish.video1.inner.com
              tags:
                - inner
          auth:
            - ak: ''
              sk: ''
              tag: 'read'
            - ak: ''
              sk: ''
              tag: 'write'
      - mifish-video-2:
          hosts:
            - host: mifish.video2.cdn.outer.com
              tags:
                - jdcdn
                - wangsucdn
            - host: mifish.video2.inner.com
              tags:
                - inner
          auth:
            - ak: ''
              sk: ''
              tag: 'read'
            - ak: ''
              sk: ''
              tag: 'write'